### ISSUE TITLE
xClusterQuorum: Fail if resource already exist

### ISSUE THREAD

**Issue by lbergeron01** [PowerShell/xFailOverCluster#197]
Running xClusterQuorum with NodeAndCloudMajority type fail if Cloud Witness already exists on the Cluster Group.

Validation/Test is required in the function.

Code used :
`        xClusterQuorum SetQuorumToNodeAndCloudMajority
        {
            IsSingleInstance        = 'Yes'
            Type                    = 'NodeAndCloudMajority'
            Resource                = $Cluster.StorageAccountName
            StorageAccountAccessKey = $Cluster.StorageAccountKey
        }`

Result :
`2018-12-13T16:19:37.3595073Z [[xClusterQuorum]SetQuorumToNodeAndCloudMajority::[cCreateCluster]CreateCluster
2018-12-13T16:19:37.3595288Z ]    at MS.Internal.ServerClusters.AzureWitnessQuorumSettings.Configure()
2018-12-13T16:19:37.3595384Z 
2018-12-13T16:19:37.3595510Z    at 
2018-12-13T16:19:37.3595648Z Microsoft.FailoverClusters.PowerShell.SetClusterQuorumCommand.WrappedProcessRec
2018-12-13T16:19:37.3595806Z ord()
2018-12-13T16:19:37.3595879Z 
2018-12-13T16:19:37.3596029Z    at Microsoft.FailoverClusters.PowerShell.FCCmdlet.ProcessRecord()
2018-12-13T16:19:37.5807110Z ##[error]An error occurred while creating resource 'Cloud Witness (2)' for the 
clustered role 'Cluster Group'.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Set-ClusterQuorum,Microsoft.FailoverClusters.Pow 
   erShell.SetClusterQuorumCommand
    + PSComputerName        : localhost
 

2018-12-13T16:19:37.5823966Z VERBOSE: [wswlcesbxvocd21]: LCM:  [ End    Set      ]  
2018-12-13T16:19:37.5824401Z [[xClusterQuorum]SetQuorumToNodeAndCloudMajority::[cCreateCluster]CreateCluster
2018-12-13T16:19:37.5824596Z ]  in 0.4060 seconds.
2018-12-13T16:19:37.5981443Z ##[error]The PowerShell DSC resource '[xClusterQuorum]SetQuorumToNodeAndCloudMajority::[
cCreateCluster]CreateCluster' with SourceInfo 'C:\VSTSAgent\_work\r1\a\Vertex-E
nv-CI\Environment\dsc\Vertex-DSCScript-ConfigureCluster-VSTS.ps1::86::9::xClust
erQuorum' threw one or more non-terminating errors while running the 
Set-TargetResource functionality. These errors are logged to the ETW channel 
called Microsoft-Windows-DSC/Operational. Refer to this channel for more 
details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost`

**Comment by johlju** [comment]
Labelling this as a bug.
